image:
  formats:
    # List of image formats you want to convert, as long as ffmpeg can decode them to y4m
    # MUST INCLUDE THE DOT
    - ".png"
    - ".jpg"
    - ".jpeg"
    - ".tif"
    - ".tiff"
    - ".bmp"
  extractor:
    - "ffmpeg"
    - "-i"
    - "{{ input }}"
    - "-strict"
    - "-2"
    - "-pix_fmt"
    - "yuv444p10le" # run ffmpeg -pix_fmts to check available pixel formats
    - "-f"
    - "yuv4mpegpipe"
    - "-y"
    - "{{ output }}"
  encoder:
    - "aomenc"
    - "--codec=av1"
    - "--allintra"
    - "--i444"
    - "--threads={{ threads }}" # auto-detects number of threads your CPU has
    - "--bit-depth=10"
    - "--max-q=63"
    - "--min-q=0"
    - "--end-usage=q"
    - "--cq-level=25"
    - "--cpu-used=6"
    - "--enable-chroma-deltaq=1"
    - "--qm-min=0"
    - "--aq-mode=1"
    - "--deltaq-mode=3"
    - "--sharpness=2"
    - "--enable-dnl-denoising=0"
    - "--denoise-noise-level=5"
    - "--tune=ssim"
    - "--width={{ width }}"
    - "--height={{ height }}"
    - "{{ input }}"
    - "--ivf"
    - "-o"
    - "{{ output }}"
  encoder_fallback: # leave this blank to disable fallback encoder
  repackager: # recommend leave this as is
    - "MP4Box"
    - "-add-image"
    - "{{ input }}:primary" # or "-:primary" for pipe mode (stdin)
    - "-ab"
    - "avif"
    - "-ab"
    - "miaf"
    - "-new"
    - "{{ output }}"
animation:
  formats:
    # SAME AS ABOVE
    - ".gif"
    - ".mp4"
    - ".webm"
  extractor:
    - "ffmpeg"
    - "-i"
    - "{{ input }}"
    - "-map"
    - "v"
    - "-strict"
    - "-2"
    - "-vf"
    # - "scale=-1:'min(1080,ih)'" # for my specific use case I don't need the height to go above 1080
    - "-pix_fmt"
    - "yuv444p10le" # run ffmpeg -pix_fmts to check available pixel formats
    - "-f"
    - "yuv4mpegpipe"
    - "-y"
    - "{{ output }}"
  encoder:
    # - "SvtAv1EncApp"
    # - "--preset"
    # - "8"
    # - "--film-grain"
    # - "2"
    # - "--progress"
    # - "5"
    # - "-b"
    # - "{{ output }}"
    # - "-i"
    # - "{{ input }}"

    - "aomenc"
    - "--codec=av1"
    - "--i444"
    - "--threads={{ threads }}" # auto-detects number of threads your CPU has
    - "--bit-depth=10"
    - "--max-q=63"
    - "--min-q=0"
    - "--end-usage=q"
    - "--cq-level=18"
    - "--cpu-used=6"
    - "--enable-chroma-deltaq=1"
    - "--qm-min=0"
    - "--aq-mode=1"
    - "--enable-dnl-denoising=0"
    - "--denoise-noise-level=5"
    - "--tune=ssim"
    - "--width={{ width }}"
    - "--height={{ height }}"
    - "--ivf"
    - "{{ input }}"
    - "-o"
    - "{{ output }}"

  encoder_fallback:
    # - "rav1e"
    # - "-v"
    # - "--speed=4"
    # - "{{ input }}"
    # - "-o"
    # - "{{ output }}"
  repackager: # recommend leave this as is
    - "ffmpeg"
    - "-i"
    - "{{ input }}"
    - "-c"
    - "copy"
    - "-map"
    - "0"
    - "-brand"
    - "avis"
    - "-f"
    - "mp4"
    - "{{ output }}"
config:
  mode: "file" # or pipe
  threads: 2
  delete_after_conversion: false
  keep_original_extension: false
  recursive: true # Also converts files in subdirectories
  overwrite: false # Overwrite converted files if they already exist
  export_log: false
